# Generated by Django 3.0.1 on 2020-12-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201219_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Tags',
            new_name='tags',
        ),
    ]
