# Generated by Django 3.0.1 on 2020-12-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201219_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delevery', 'out for delevery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
