# Generated by Django 3.0.1 on 2020-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201220_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delevery', 'Out for delevery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
